#!/usr/bin/env bash
make clean FPC=fpc CPU_TARGET=arm OS_TARGET=freertos CROSSOPT="$MYOPTARM" SUBARCH=armv7em OVERRIDEVERSIONCHECK=1 "$@" -j
time make all FPC=fpc CPU_TARGET=arm OS_TARGET=freertos CROSSOPT="$MYOPTARM" SUBARCH=armv7em OVERRIDEVERSIONCHECK=1 "$@" -j
