#!/usr/bin/env bash
set -e

make CPU_TARGET=arm OS_TARGET=linux clean -j
CPU=`uname -p`

if [ -z "$1" ]
then
  if [ $CPU == "armv7l" ];
  then
    RUNMODE=native
  else
    RUNMODE=cross
  fi
else
  RUNMODE=$1
fi

CROSSOPT="$MYOPTARM -Xr/usr/arm-linux-gnueabihf -XR/usr/arm-linux-gnueabihf"

case "$RUNMODE" in
   native) time make all FPC=fpc CPU_TARGET=arm OS_TARGET=linux OPT="$MYOPTARM" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   cross)  time make all FPC=fpc CPU_TARGET=arm OS_TARGET=linux CROSSOPT="$CROSSOPT" OPT=-dFPC_ARMHF OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   qemu)   OLD_LD_PREFIX=$QEMU_LD_PREFIX
           OLD_BINUTILSPREFIX=$BINUTILSPREFIX
           export QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf
           export BINUTILSPREFIX=arm-linux-

           time make all FPC=ppcarm NOWPOCYCLE=1 CPU_TARGET=arm OS_TARGET=linux BINUTILSPREFIX=arm-linux- OPT="$CROSSOPT" OVERRIDEVERSIONCHECK=1 "$@" -j

           export BINUTILSPREFIX=$OLD_BINUTILSPREFIX
           export QEMU_LD_PREFIX=$OLD_QEMU_LD_PREFIX ;;
esac
