#!/bin/bash
set -e
rm -f build-stamp.avr-embedded
if [ -z "$SUBARCH" ]
then
  SUBARCH=avr5
fi
time make all OVERRIDEVERSIONCHECK=1 "$@" -j "OPTNEW=$MYOPTAVR -vbr" OPT=-"vbr $MYOPTA64" "OS_TARGET=embedded" "CPU_TARGET=avr" "SUBARCH=$SUBARCH"
