#!/bin/bash
set -e
rm -f build-stamp.avr-embedded
CPU=`uname -m`

case "$CPU" in
   aarch64) OPT="-vbr $MYOPTA64" ;;
   amd64|x86_64) OPT="-vbr $MYOPTX64" ;;
   i386|i586|i686) OPT="-vbr $MYOPT386" ;;
esac

if [ -z "$SUBARCH" ]
then
  SUBARCH=avr5
fi
time make all OVERRIDEVERSIONCHECK=1 "OPTNEW=$MYOPTAVR -vbr" OPT="$OPT $OS_HOST_OPT" "OS_TARGET=embedded" "CPU_TARGET=avr" "SUBARCH=$SUBARCH" "$@" -j
