#!/bin/bash
set -e
make distclean || true
if [ -z "$3" ]
then
  if [ "$2" == "nogdb" ]
  then
    ./configure --target=$1 --disable-gdb --disable-sim --disable-readline --disable-libdecnumber
  else
    ./configure --target=$1
  fi
else
  if [ "$3" == "nogdb" ]
  then
    ./configure --target=$1 --program-prefix=$2 --disable-gdb --disable-sim --disable-readline --disable-libdecnumber
  else
    ./configure --target=$1 --program-prefix=$2
  fi
fi

make -j `nproc`
sudo make install
make distclean
