#!/usr/bin/env bash
make distclean -j
CPU=`uname -m`
OS_TARGET=iphonesim

if [ -z "$1" ]
then
  RUNMODE=cross
else
  RUNMODE=$1
fi

CROSSOPT="$MYOPTA64 -XR/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"

case "$RUNMODE" in
   cross)  time make all NOWPOCYCLE=1 FPC=fpc CPU_TARGET=aarch64 OS_TARGET=$OS_TARGET CROSSOPT="$CROSSOPT" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
esac
