#!/usr/bin/env bash
make clean -j
CPU=`uname -p`

if [ -z "$1" ]
then
  if [ $CPU == "mips" ];
  then
    RUNMODE=native
  else
    RUNMODE=cross
  fi
else
  RUNMODE=$1
fi

case "$RUNMODE" in
   native) time make all FPC=fpc CPU_TARGET=mips OS_TARGET=linux OPT="$MYOPTMIPS" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
#   cross)  time make all FPC=fpc NOWPOCYCLE=1 CPU_TARGET=mips OS_TARGET=linux BINUTILSPREFIX=mips-linux- CROSSOPT="$MYOPTMIPS -Xr/usr/mips-linux-gnu -XR/usr/mips-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   cross)  time make all FPC=fpc NOWPOCYCLE=1 CPU_TARGET=mips OS_TARGET=linux BINUTILSPREFIX=mips-linux- OPT="$OS_HOST_OPT" CROSSOPT="$MYOPTMIPS -Xr/usr/mips-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   qemu)   OLD_LD_PREFIX=$QEMU_LD_PREFIX
           export QEMU_LD_PREFIX=/usr/mips-linux-gnu
           time make all FPC=ppcmips NOWPOCYCLE=1 CPU_TARGET=mips OS_TARGET=linux BINUTILSPREFIX=mips-linux- OPT="$MYOPTMIPS -Xr/usr/mips-linux-gnu -XR/usr/mips-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j
           export QEMU_LD_PREFIX=$OLD_QEMU_LD_PREFIX ;;
esac
