#!/usr/bin/env bash
make clean -j
CPU=`uname -p`

if [ -z "$1" ]
then
  if [ $CPU == "mipsel64" ];
  then
    RUNMODE=native
  else
    RUNMODE=cross
  fi
else
  RUNMODE=$1
fi

case "$RUNMODE" in
   native) time make all FPC=fpc CPU_TARGET=mipsel64 OS_TARGET=linux OPT="$MYOPTMIPSEL64" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
#   cross)  time make all FPC=fpc NOWPOCYCLE=1 CPU_TARGET=mipsel64 OS_TARGET=linux BINUTILSPREFIX=mipsel64-linux- CROSSOPT="$MYOPTmipsel64 -Xr/usr/mipsel64-linux-gnu -XR/usr/mipsel64-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   cross)  time make all FPC=fpc NOWPOCYCLE=1 CPU_TARGET=mipsel64 OS_TARGET=linux BINUTILSPREFIX=mipsel64-linux- OPT="$OS_HOST_OPT" CROSSOPT="$MYOPTMIPSEL64 -Xr/usr/mipsel64-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   qemu)   OLD_LD_PREFIX=$QEMU_LD_PREFIX
           export QEMU_LD_PREFIX=/usr/mipsel64-linux-gnu
           time make all FPC=ppcmipsel64 NOWPOCYCLE=1 CPU_TARGET=mipsel64 OS_TARGET=linux BINUTILSPREFIX=mipsel64-linux- OPT="$MYOPTMIPSEL64 -Xr/usr/mipsel64-linux-gnu -XR/usr/mipsel64-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j
           export QEMU_LD_PREFIX=$OLD_QEMU_LD_PREFIX ;;
esac
