#!/usr/bin/env bash
make clean -j
CPU=`uname -p`

if [ -z "$1" ]
then
  if [ $CPU == "mips64el" ];
  then
    RUNMODE=native
  else
    RUNMODE=cross
  fi
else
  RUNMODE=$1
fi


case "$RUNMODE" in
   native) time make all FPC=fpc CPU_TARGET=mips64el OS_TARGET=linux OPT="$MYOPTMIPS64EL" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
#   cross)  time make all FPC=fpc NOWPOCYCLE=1 CPU_TARGET=mipsel OS_TARGET=linux BINUTILSPREFIX=mipsel-linux- CROSSOPT="$MYOPTMIPSEL -Xr/usr/mipsel-linux-gnu -XR/usr/mipsel-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   cross)  time make all FPC=fpc NOWPOCYCLE=1 CPU_TARGET=mips64el OS_TARGET=linux BINUTILSPREFIX=mipsel-linux- CROSSOPT="$MYOPTMIPS64EL -Xr/usr/mips64el-linux-gnuabi64" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   qemu)   OLD_LD_PREFIX=$QEMU_LD_PREFIX
           export QEMU_LD_PREFIX=/usr/mips64el-linux-gnu
           time make all FPC=ppcmips64el NOWPOCYCLE=1 CPU_TARGET=mips64el OS_TARGET=linux BINUTILSPREFIX=mips64el-linux- OPT="$MYOPTMIPS64EL -Xr/usr/mips64el-linux-gnuabi64 -XR/usr/mips64el-linux-gnuabi64" OVERRIDEVERSIONCHECK=1 "$@" -j
           export QEMU_LD_PREFIX=$OLD_QEMU_LD_PREFIX ;;
esac
