#!/usr/bin/env bash
make clean -j
CPU=`uname -p`

if [ -z "$1" ]
then
  if [ $CPU == "powerpc64le" ];
  then
    RUNMODE=native
  else
    RUNMODE=cross
  fi
else
  RUNMODE=$1
fi


case "$RUNMODE" in
   native) time make all FPC=fpc CPU_TARGET=powerpc OS_TARGET=linux OPT="$MYOPTPPC" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   cross)  time make all FPC=fpc NOWPOCYCLE=1 CPU_TARGET=powerpc64 OS_TARGET=linux BINUTILSPREFIX=powerpc64le-linux- CROSSOPT="$MYOPTPPC -Xr/usr/powerpc64le-linux-gnu -XR/usr/powerpc64le-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   qemu)   OLD_LD_PREFIX=$QEMU_LD_PREFIX
           export QEMU_LD_PREFIX=/usr/powerpc64le-linux-gnu
           time make all FPC=ppcppc NOWPOCYCLE=1 CPU_TARGET=powerpc64 OS_TARGET=linux BINUTILSPREFIX=powerpc64le-linux- OPT="$MYOPTPPC -Xr/usr/powerpc64le-linux-gnu -XR/usr/powerpc64lelinux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j  
           export QEMU_LD_PREFIX=$OLD_QEMU_LD_PREFIX ;;
esac
