#!/usr/bin/env bash
set -e
if [ -z "$1" ]
then
  echo Missing suffix
else
  cd $MYFPCDIR/$MYFPC/rtl/linux
  make distclean FPC=$MYFPCDIR/$MYFPC/compiler/powerpc/pp "OPT=@~/bin/fpc.cfg -al $MYOPTPPC"
  make all FPC=$MYFPCDIR/$MYFPC/compiler/powerpc/pp "OPT=@~/bin/fpc.cfg -vi -al $MYOPTPPC" -j
  cd ..
  rm -rf units.$1
  cp -a units units.$1
fi
