#!/usr/bin/env bash
set -e
if [ -z "$1" ]
then
  echo Missing suffix
else
  cd $MYFPCDIR/$MYFPC/rtl/linux
  make distclean FPC=$MYFPCDIR/$MYFPC/compiler/sparc/pp PP=$MYFPCDIR/$MYFPC/compiler/i386/pp "OPT=@~/bin/fpc.cfg -al $MYOPTSPARC"
  make all FPC=$MYFPCDIR/$MYFPC/compiler/sparc/pp PP=$MYFPCDIR/$MYFPC/compiler/i386/pp "OPT=@~/bin/fpc.cfg -vi -al $MYOPTSPARC" -j
  cd ..
  rm -rf units.$1
  cp -a units units.$1
fi
