#!/usr/bin/env bash
set -e
if [ -z "$1" ]
then
  echo Missing suffix
else
  cd $MYFPCDIR/$MYFPC/rtl/linux
  make distclean FPC=$MYFPCDIR/$MYFPC/compiler/m68k/pp "OPT=@~/bin/fpc.cfg -al $MYOPTM68k"
  make all FPC=$MYFPCDIR/$MYFPC/compiler/m68k/pp "OPT=@~/bin/fpc.cfg -vi -al $MYOPTM68K" -j
  cd ..
  rm -rf units.$1
  cp -a units units.$1
fi
