#!/usr/bin/env bash
set -e
if [ -z "$1" ]
then
  echo Missing suffix
else
  cd $MYFPCDIR/$MYFPC/rtl/embedded
  make distclean FPC=$MYFPCDIR/$MYFPC/compiler/avr/pp PP=$MYFPCDIR/$MYFPC/compiler/i386/pp "OPT=@~/bin/fpc.cfg -al $MYOPTAVR" SUBARCH=avr5
  make all FPC=$MYFPCDIR/$MYFPC/compiler/avr/pp PP=$MYFPCDIR/$MYFPC/compiler/i386/pp "OPT=@~/bin/fpc.cfg -vi -al $MYOPTAVR" SUBARCH=avr5 -j
  cd ..
  rm -rf units.$1
  cp -a units units.$1
fi
