#!/usr/bin/env bash
set -e
if [ -z "$1" ]
then
  echo Missing suffix
else
  cd $MYFPCDIR/$MYFPC/rtl/freertos
  make distclean FPC=$MYFPCDIR/$MYFPC/compiler/xtensa/pp PP=fpc "OPT=@~/bin/fpc.cfg -al $MYOPTXTENSA" OS_TARGET=freertos SUBARCH=lx6 -j
  make all FPC=$MYFPCDIR/$MYFPC/compiler/xtensa/pp PP=fpc OS_TARGET=freertos "OPT=@~/bin/fpc.cfg -vi -al $MYOPTXTENSA -Cplx6 -XPxtensa-esp32-elf- -Cfhard" SUBARCH=lx6 -j
  cd ..
  rm -rf units.$1
  cp -a units units.$1
fi
