#!/usr/bin/env bash
set -e
if [ -z "$1" ]
then
  echo Missing suffix
else
  cd $MYFPCDIR/$MYFPC/rtl/`$MYFPCDIR/"$MYFPC"compiler/ppcx64 -iTO`
  make distclean FPC=$MYFPCDIR/"$MYFPC"compiler/ppcx64 "OPT=@~/bin/fpc.cfg -alt $MYOPTX64" -j
  make all FPC=$MYFPCDIR/"$MYFPC"compiler/ppcx64 "OPT=@~/bin/fpc.cfg -vi -alt $MYOPTX64" -j
  cd ..
  rm -rf units.$1
  cp -a units units.$1
fi
