#!/bin/bash
set -e

if [ -z "$1" ]
then
  echo Missing suffix
else
  cd ~/fpc/$MYFPC
  mkdir output.$1
  make distclean OVERRIDEVERSIONCHECK=1 "OPTNEW=$MYOPTX64 -al" -j
  # add || true so we copy always
  make all OVERRIDEVERSIONCHECK=1 "OPTNEW=$MYOPTX64 -al" -j NOWPOCYCLE=1 || true
  find rtl/units -name \*.s -exec cp {} output.$1 \; 
  find compiler -name \*.s -exec cp {} output.$1 \;
  find packages -name \*.s -exec cp {} output.$1 \;
fi
