#!/bin/bash
set -e

if [ -z "$1" ]
then
  echo Missing suffix
else
  cd ~/fpc/$MYFPC
  mkdir output.$1
  make distclean OVERRIDEVERSIONCHECK=1 "CROSSOPT=$MYOPTA64 -al" -j
  make all OVERRIDEVERSIONCHECK=1 "CROSSOPT=$MYOPTA64 -al" "OPT=$MYOPT" -j NOWPOCYCLE=1 CPU_TARGET=aarch64
  find rtl/units -name \*.s -exec cp {} output.$1 \;
  find compiler -name \*.s -exec cp {} output.$1 \;
  find packages -name \*.s -exec cp {} output.$1 \;
fi
