#!/usr/bin/env bash
make clean -j
CPU=`uname -p`

if [ -z "$1" ]
then
  if [ $CPU == "sparc64" ];
  then
    RUNMODE=native
  else
    RUNMODE=cross
  fi
else
  RUNMODE=$1
fi

FPCCPU=sparc64

case "$RUNMODE" in
   native) time make all FPC=fpc CPU_TARGET=$(FPCCPU) OS_TARGET=linux OPT="$MYOPTSPARC64" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   cross)  time make all FPC=fpc NOWPOCYCLE=1 CPU_TARGET="$FPCCPU" OS_TARGET=linux BINUTILSPREFIX="$FPCCPU-linux-" CROSSOPT="$MYOPTSPARC64 -Xr/usr/$(FPCCPU)-linux-gnu -XR/usr/$(FPCCPU)-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j ;;
   qemu)   OLD_LD_PREFIX=$QEMU_LD_PREFIX
           export QEMU_LD_PREFIX="/usr/$FPCCPU-linux-gnu"
           time make all FPC=ppcsparc64 NOWPOCYCLE=1 CPU_TARGET="$FPCCPU" OS_TARGET=linux BINUTILSPREFIX="$FPCCPU-linux-" OPT="$MYOPTSPARC64 -Xr/usr/$FPCCPU-linux-gnu -XR/usr/$FPCCPU-linux-gnu" OVERRIDEVERSIONCHECK=1 "$@" -j
           export QEMU_LD_PREFIX="$OLD_QEMU_LD_PREFIX" ;;
esac
