#!/usr/bin/env bash
make OS_TARGET=wasi CPU_TARGET=wasm32 BINUTILSPREFIX= OPT="-O-" clean -j
time make all FPC=fpc OS_TARGET=wasi CPU_TARGET=wasm32 BINUTILSPREFIX= OPT="-O-" OVERRIDEVERSIONCHECK=1 "$@" -j
