#!/bin/bash
set -e

if [ -z "$1" ]
then
  echo Missing suffix
else
  cd ~/fpc/$MYFPC
  mkdir output.$1
  find rtl/units -name \*.s -exec cp {} output.$1 \;
  find compiler -name \*.s -exec cp {} output.$1 \;
  find packages -name \*.s -exec cp {} output.$1 \;
fi
