#!/bin/bash
FULLTARGET=i386-linux
cp output/$FULLTARGET/log log.$FULLTARGET.$1
cp output/$FULLTARGET/longlog longlog.$FULLTARGET.$1
cp output/$FULLTARGET/faillist faillist.$FULLTARGET.$1
old=$(expr $1 - 1)
diff faillist.$FULLTARGET.$old faillist.$FULLTARGET.$1
