#!/bin/bash
if [ -z "$1" ]
then
  echo Missing number
  exit 1
fi
if [ -z "$2" ]
then
  echo Missing target
  exit 1
else
  FULLTARGET=$2
fi
if [ $# -eq 3 ]
then
  LOGPOSTFIX=$3
else
  LOGPOSTFIX=$FULLTARGET
fi
echo Using sequential number $1
echo Copying to tests/log.$LOGPOSTFIX.$1
cp output/$FULLTARGET/log log.$LOGPOSTFIX.$1
echo Copying to tests/longlog.$LOGPOSTFIX.$1
cp output/$FULLTARGET/longlog longlog.$LOGPOSTFIX.$1
echo Copying to tests/faillist.$LOGPOSTFIX.$1
cp output/$FULLTARGET/faillist faillist.$LOGPOSTFIX.$1
difflogx $1 $LOGPOSTFIX
