#!/bin/bash
if [ -z "$1" ]
then
  echo Missing number
  exit 1
fi
if [ -z "$2" ]
then
  echo Missing target
  exit 1
else
  FULLTARGET=$2
fi
echo Using sequential number $1
echo Copying to tests/log.$FULLTARGET.$1
cp output/$FULLTARGET/log log.$FULLTARGET.$1
echo Copying to tests/longlog.$FULLTARGET.$1
cp output/$FULLTARGET/longlog longlog.$FULLTARGET.$1
echo Copying to tests/faillist.$FULLTARGET.$1
cp output/$FULLTARGET/faillist faillist.$FULLTARGET.$1
old=$(expr $1 - 1)
diff faillist.$FULLTARGET.$old faillist.$FULLTARGET.$1
