#!/usr/bin/env bash
if [ -f ~/fpc/"$MYFPC"compiler/ppcrossa64 ]; then
    FPC=~/fpc/"$MYFPC"compiler/ppcrossa64
else
    FPC=~/fpc/"$MYFPC"compiler/ppca64
fi
make FPC=$FPC "OPT=@/home/florian/bin/fpc.cfg -Fl/usr/$CPU-linux-gnu/lib/ -O4" $@  -j
