#!/bin/bash
set -e
BRANCH=$(date '+%Y%m%d%H%M%S');
echo Going to commit $BRANCH
git branch $BRANCH
git checkout $BRANCH

if [ -z "$1" ]
then
  git commit -a
else
  git commit $@
fi
git push origin $BRANCH
