#!/bin/bash
set -e
BRANCH=$(date '+%Y_%m_%d__%H_%M_%S');
echo Going to commit $BRANCH
git branch $BRANCH
git checkout $BRANCH

if [ -z "$1" ]
then
  git commit -a
else
  git commit $@
fi
git push origin $BRANCH
remote_dcommit $BRANCH
