#!/bin/bash
set -e
cmd1="cd $DCOMMIT_REMOTE_GITDIR && git rebase"
if [ -z "$1" ]
then
  curr_branch=`git rev-parse --abbrev-ref HEAD`
else
  curr_branch=$1
  cmdall="$cmd1 $1"
fi
  cmdall="$cmd1 $curr_branch"
ssh $DCOMMIT_REMOTE "$cmdall"
ssh $DCOMMIT_REMOTE "cd $DCOMMIT_REMOTE_GITDIR && git svn rebase && git svn dcommit -n"
ssh $DCOMMIT_REMOTE "cd $DCOMMIT_REMOTE_GITDIR && git log -n 5 && echo Press key to continue && read -n1 -s"
ssh $DCOMMIT_REMOTE "cd $DCOMMIT_REMOTE_GITDIR && git svn dcommit"
cd $MYFPCDIR/$MYFPC
ssh $DCOMMIT_REMOTE "cd $DCOMMIT_REMOTE_GITDIR && git svn rebase"
git fetch -a
git checkout -B master remotes/origin/master --
git push origin --delete $curr_branch
git branch -D $curr_branch
git log HEAD -n 3
