#!/usr/bin/env bash

WORKING=11000
FAILING=11476
FPCDIR=~/fpc
FPCOPTS=
COMMAND=cd ~/fpc && ~/bin/fpc11x64 tmdtest

COUNT=0
while [ $[$FAILING-$WORKING] -gt 1 ]; do
  TESTREV=$[($FAILING-$WORKING)/2+$WORKING]
  echo "Testing revision $TESTREV"
  COUNT=$[$COUNT+1]
  (
    cd $FPCDIR
    make distclean
    svn up -r $TESTREV
    make all OPT=$FPCOPTS && $COMMAND
  )
  if [ $? != 0 ]; then
    echo "Testing revision $TESTREV failed"
    FAILING=$TESTREV
  else
    echo "Testing revision $TESTREV succeeded"
    WORKING=$TESTREV
  fi
done

echo "Last working revision: $WORKING (needed $COUNT runs)"
