#!/usr/bin/env bash
set -e
if [ -z "$1" ]
then
  echo Missing target
  exit 1
else
  FULLTARGET=$1
fi
if [ $# -eq 2 ]
then
  LOGPOSTFIX=$2
else
  LOGPOSTFIX=$FULLTARGET
fi
a=`ls log.$LOGPOSTFIX.* | egrep -o "[0-9]+$" | awk '{if ($1 > max) max=$1} END {print max}'`
a=$(expr $a + 1)
echo Copying to $a
cplogx $a $FULLTARGET $LOGPOSTFIX
