#!/usr/bin/env bash
set -e
if [ -z "$1" ]
then
  echo Missing target
  exit 1
else
  FULLTARGET=$1
fi
if [ $# -eq 2 ]
then
  LOGPOSTFIX=$2
else
  LOGPOSTFIX=$FULLTARGET
fi
a=1
while [ -f log.$LOGPOSTFIX.$a ] ;
do
  a=$(expr $a + 1)
done
echo Copying to $a
cplogx $a $FULLTARGET $LOGPOSTFIX
