#!/bin/bash
CURRENT_PATH=`pwd`
make clean TEST_FPC="$CURRENT_PATH/../compiler/ppcx64" V=1 TEST_OPT="$MYTEST_OPTX64"
make full TEST_DELTEMP=1 TEST_FPC="$CURRENT_PATH/../compiler/ppcx64" V=1 TEST_OPT="$MYTEST_OPTX64" -j 20
