#!/usr/bin/env bash
set -e
set -x
CURRENT_PATH=`pwd`
export LD_PRELOAD=
export QEMU_LD_PREFIX=/usr/m68k-linux-gnu
time make full TEST_DELTEMP=1 FPCDIR=$CURRENT_PATH/.. FPC=fpc TEST_FPC=$CURRENT_PATH/../compiler/ppcross68k TEST_CPU_TARGET=m68k TEST_OS_TARGET=linux V=1 \
TEST_OPT="-XPm68k-linux-gnu- $MYTEST_OPT68K -Fd -Foobj/linux/m68k -XR/usr/m68k-linux-gnu -Fl/usr/lib/gcc-cross/m68k-linux-gnu/9/ -vbr" EMULATOR=qemu-m68k -j 16
