#!/usr/bin/env bash
set -e
make distclean TEST_DELTEMP=1 FPC=$PWD/../compiler/ppcx64 TEST_FPC=$PWD/../compiler/ppcrossavr V=1 "TEST_SUBARCH=avr6" "TEST_OPT=$MYTEST_OPTAVR" "$@" "TEST_VERBOSE=1"
make full TEST_DELTEMP=1 FPCFPMAKE=$PWD/../compiler/ppcx64 TEST_FPC=$PWD/../compiler/ppcrossavr V=1 "TEST_SUBARCH=avr6" "TEST_OPT=$MYTEST_OPTAVR -XPavr-embedded- -Wpavrsim6" TEST_TIMEOUT=120 EMULATOR=~/fp-avrsim/avrsim EMULATOR_OPTS=-6 -j "$@"
